### ISSUE TITLE
v6 Accessibility by blind hams

### ISSUE THREAD

**Issue by vk7js** [afarhan/ubitxv6#1]
Hi. My name is Joseph Stephen, vk7js. I am a totally blind software engineer as well as an advanced amateur radio licence holder from VK. I have been reviewing your firmware for v6 and noted that you have a morse field for each button. I am wondering if this is to eventually provide CW feedback for the touch screen controls? I'd love to contribute to this project to either make the UBitX v6 totally accessible via CW or via speech output. I do not have a kit as yet. Please write to me off list at joestephen@skymesh.com.au if you would be interested in me helping you make this project accessible for blind hams of which there are many. It would be wonderful if we could produce an accessible multiband transceiver for under $250 USD. Most blind hams are not financial. I am of course willing to donate my programming time. I would however apreciate a kit that I can test changes on.

**Comment by afarhan** [comment]
Joseph,
I have planned to make the ubitx fully accessible. Let me refactor the code
and add the basic morse reading capability. You can then get in and start
hacking away! I will get to it only by1st week of January.
Thanks for the offer of help. I much appreciate it.
73, f

**Comment by vk7js** [comment]
Hi Ashhar,

 

Thanks so much for your reply. I’ll gladly help you do the programming.

Here’s what I’d like to do:

1.	As well as your touch screen interface, I’d like to also include your v5 knob support to select and activate menus as I think the touch screen will be too difficult for some blind users since as soon as they touch the screen it will change settings rather than just select the  item. So, you should be able to interact with the UBitX either via the touch screen or via the older turning and pressing of knob.
2.	I’d like to investigate if the Talkie library can be used to provide speech feedback. I’m not sure if with your current firmware there will be enough memory. Obviously we’ll get CW feedback working first but if we can get speech feedback working using a library such as Talkie, that would be extremely good. I’ve been a programmer for 25 plus years so should be able to get up and running with Arduino quickly so long as the IDE is accessible or there is a commandline compiler.

Would you be able to send me a kit to experiment with? If so, my address is

608 Rookery Roadd, 

Winkleigh TAS 7275

Australia

Tel: +61 416 090232

 

Thanks for your work on this.

 

Joseph

**Comment by vk7js** [comment]
Hi Ashhar,

 

Here’s a link to the Talkie sample: https://rimstar.org/science_electronics_projects/ardunio_speech_synthesizer_using_talkie_library.htm

I don’t know if you already have this set up with an lm386 amp the way this circuit suggests. If so, assuming there is sufficient memory, this shouldn’t be too hard to do. As I said, I’m happy to do it so long as we have the hardware resources available.

Joe

**Comment by afarhan** [comment]
It will be difficult for me to ship a kit soon. Probably end of january.
They are swamped with orders right now. Thats when the next batch will
start production.
We have less than 1k of code space left. I will be able to do only morse.
What speed should it read out at?

**Comment by vk7js** [comment]
Hi Ashhar, probably same speed as the cw keyer is set to.

I’ll do some research as to how much space the Talkie library requires but CW will be a great start.

Thanks

Joe

**Comment by vk7js** [comment]
Ashhar, exactly which arduino board does your project use and how much memory does it come with? Is it possible later to add more memory? Just thinking ahead to options for adding speech. Talkie uses timers 1 and 2 and pin 3 for audio so if UBitX already use these, I guess we could add a 2nd Arduino board or modify the library.   

Thanks

Joe

**Comment by vk7js** [comment]
Hi Ashhar, just a reminder to please send me that test kit for accessibility.

 

Joseph Stephen

608 Rookery Road,

Winkleigh TAS 7275

Australia

Tel: +61 416090232

Thanks

Joseph

**Comment by vk7js** [comment]
Hi Ashhar,

 

Have you been able to send me a test kit with the cw accessibility feedback yet? Please send to 

Joseph Stephen

608 Rookery Rd,

Winkleigh TAS 7275

Australia

Tel: +61 416090232

Thanks

Joseph

**Comment by vk7js** [comment]
Hi Ashhar,

 

Have you been able to send me a test kit with the cw accessibility feedback yet? Please send to 

Joseph Stephen

608 Rookery Rd,

Winkleigh TAS 7275

Australia

Tel: +61 416090232

Thanks

Joseph

**Comment by vk7js** [comment]
Hi Ashhar,

Would you please send me that kit so I can continue improving the accessibility of the firmware?

Joseph Stephen

608 Rookery Rd, Winkleigh TAS 7275

Australia.

Thanks

Joseph

**Comment by afarhan** [comment]
Joseph,
I am so sorry I dropped the ball on this. I am ccing my colleague thomas we
will despatch the kit immediately.
I made some progress in assigning morse readable text tokens to each touch
button on the.display and i also made it entirely navigatable by thr
encoder alone. I didnt get around to making it speak in morse code.
Thomas, will you take care to have one ubitx shipped out to joseph? He is
will adapt to be usable by the blind.
73, f

**Comment by vk7js** [comment]
Thanks Ashhar.

Joe

Vk7js

**Comment by vk7js** [comment]
Hi Ashhar,

 

As soon as the UBitX arrives (which should be any day now), I’d like to be ready with the programming environment. Please would you provide the following information for me:

1.	Official repo and branch from github that I should be working in.
2.	A quick summary of what you have already done in terms of cw feedback (if any).
3.	The exact hardware configuration and any setup steps for the IDE and any SDK I should be using in order to build the project.

Will the version of the kit have hardware controls or only a touch screen? If hardware controls, my goal would be to ensure that whatever can be done via the touch screen can be done via the hardware controls with cw or spoken voice prompts.

Thanks

Joe

Vk7js

**Comment by vk7js** [comment]
Hi Afarhan,

 

The UBitX arrived today. Please send link to github official repo and dev
branch and I'll begin looking at it.

Thanks

Joe

**Comment by afarhan** [comment]
Joe,
Sorry for the very late reply.
1. The repo that you should work on is https://github.com/afarhan/ubitxv6
2. The user interface is coded in the file named ubitx_ui.cpp. All the user
interface elements are treated as buttons with their individual x, y
locations and widths and heights. This struct button is defined on line 17.
Using this structure, we construct the user interface as an array of
buttons. This is on line 24 onwards. You will notice that the last element
of each button is a one or two letter mnemonic. This is meant to be read
out in morse.
3. The way it works is like this. If you tap the encoder switch the tuning
knob changes from being a tuning knob to being a selector of the buttons. A
rectangle frame is draw around the button that the encoder is pointing to.
Much of this code is in the function doCommand starting from line 605. The
function drawFocus does that. We will have to parallely add code to read
out the buttons in morse code.
4. The morse code reader is in the files morse.cpp and morse.h. The
function morseLetter sends out one letter to the speaker and morseText
sends out a string.

In summary, the soft buttons already have provision of text labels that can
be quickly read out to the operator. The morse reader is also in place. At
the moment, the morse reader blocks any other code from executing. We can
tackle this in two ways: 1. make the morseText work in the background and
it should be abort as soon as you change the encoder or 2. Keep the morse
read out very short.
The frequency is also a button with the frequency as the text displayed on
the button. You will have to handle it specially to read out the frequency
from the text field of the struct button and not the morse field (or both!).
The first three buttons are VFO A, VFO B and RIT. For these three, you will
need to add reading out of the text fields in addition to the morse field.
The frequency read out is 8 to 10 digits long, in between letters, you can
poll to see if the encoder has changed or the switch has been pressed. the
functions to do that are enc_read and btnDown.
I hope things are explicit. Once you start getting deeper into this, you
will have more questions. Do write to me or at the bitx20 group.
All the best!

73, f

**Comment by vk7js** [comment]
Hi Ashhar,

 

Thanks for this. Yes, I’ve familiarized myself with the code but haven’t yet built it or uploaded to the radio. I need to figure out how to do that. I was going to play with the talkie library to see how much overhead that would incur to add speech. I suspect I’ll have to stick with the morse code.

Thanks again

 

Joe

**Comment by vk7js** [comment]
Hi Ashhar,

 

Once I work out how to build and upload the firmware (any tips that would be helpful?) I will make it so that the morse read out can be interrupted. Then, when the button is released or the tuning knob stops, I’ll play the button mnemonic or the frequency depending on the mode. If this morse reader is enabled,  I’ll probably need to adjust the code in the touch screen logic so that when a person moves their finger over the screen, the morse will play when their finger lands on a button, but will not activate unless they double tap the button. Otherwise it would be too difficult because the buttons would accidentally activate when exploring the screen.

I really want to make it so that you can enable the morse reader on power-on, e.g. hold down the encoder when powering on. If not, it wil be difficult for the user to enable the mode.

I think you have something else configured right now if someone holds the encoder down while powering on, would you explain that?

Thanks

Joe

**Comment by afarhan** [comment]
Joe,
it would be best if you tried using the AVR dude, which is a command line
version. I personally prefer that. You will certainly find details about it
on the net. Let me figure it out and i will give you a summary soon.
- f

**Comment by vk7js** [comment]
Hi Farhan,

 

Can I confirm that the exact functionality available via the touch screen is the same as what is available by quickly pressing the knob and rotating it?

This appears to be the case looking at the source code.

If so, while we could make the touch screen accessible, it is a bit more work. What we’d have to do is not perform the action when a button was touched, but play the morse code for the button, and only perform the action if the button was touched rapidly after the morse code was played, i.e. detect a double click.

It might be simpler, if the functionality is the same using the encoder, just to make that accessible. When the encoder is rotated after the quick press, play the morse code as the selector lands on the new button. When the encoder is pressed to select the button, play the morse code for the new state of the button.

Of course, in the morseText Function, bail return early if the button state or encoder state changeswhile the text is being sent. DO this by recording the encoder and button state prior to entering the morse loopp, and then checking inside the loop and returning if the state of either the encoder or button changes.

That way, at most you’d only have to wait until the current character had finished being played.

It would of course be nice to also support the touch screen, if the user touches the button showing the frequency, we can play it.

I just need to know how to upload to the radio to test.

Please send the summary when you can.

Thanks

Joe

**Comment by afarhan** [comment]
Joseph,
It would perhaps be best if we start a thread on the bitx20 group on
groups.io.
I think, not sure, that i wrote the morse reader so it plays the morse code
without blocking. I will have to check it to confirm.
Right from the start, ubitx6 was coded such that could work without visual
cues. I personally need it to operate while i am in bed or operating under
bright sunlight in the field.
The encoder steps through all the menu items that are laid out as visual
buttons.
Btw, i am building an sdr that will work with command line as well. I hope
you will find that useful too.
- f

**Comment by vk7js** [comment]
Hi F,

 

The SDR would be great. I think if it is based on Arduino, would you consider a larger memory model so you can include the Talkie library? If this is a standalone scanner, I know for sure that many blind people would love it as there is absolutely nothing out there which is accessible in the way of digital scanners.

Joe

**Comment by vk7js** [comment]
Hi Farhan,

 

Here are the changes I propose to make:

 

1.	Currently, the morseText function is never called, presumably because most people don’t want cw feedback. Because a blind person can’t choose this from the menu on initial power on, and since DoSetup2 is already available by holding down the encoder, I propose to change the holding down encoder while powering on to enable Accessible mode (cw feedback) rather than immediately going to DoSetup2. As stated, a user can already go to the DoSetup2 menu by holding the encoder longer. This way, a blind person can receive the kit, hold down the encoder while powering on and get cw feedback without having to get a sighted person to enable it from the menu (and there is no menu option for it anyway).
2.	I’ve added logic to cancel the morseText if while it is playing, the encoder is pressed or turned. This way, it can be interrupted.
3.	I propose to call MorseText when the encoder settles on a menu option and when the option changes so that a blind person can hear the menu options being chosen and know what they chose.
4.	I will need to experiment with the touch screen to see how easy it is to support this in explore mode, i.e. play the cw for the option touched, and only activate it on a double touch. I don’t know how well this will work. The only real advantage to supporting the touch screen, since most functions can be gotten to through the menu, is direct frequency entry and also to touch the frequency display and hear the frequency readout in cw.

	I still need however your summary as to how to build and upload the firmware to the radio.

	 

	Thanks

	Joseph

**Comment by vk7js** [comment]
Hi Farhan,

 

I’m getting there, I watched (listened) to your video on uploading. The problem is I’m getting an avrdude error when I try uploading.

I don’t know if I have all the right settings.

Here are my settings:

Board: Arduino Nano

Processor: atmega328p

Which programmer should I have selected? I’ve tried several.

Also, what should be the com port settings? I tried setting at 38400 since that is what the Setup function initializes the port to.

Thanks

Joe

**Comment by vk7js** [comment]
Here are the errors I\m getting when trying to upload:

Should I have the power cord connected and the power knob on or off? Or should I only have the USB cable connected? Ive verified that the com port is correct.

Thanks

         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

         Copyright (c) 2007-2014 Joerg Wunsch

 

         System wide configuration file is "C:\Arduino\hardware\tools\avr/etc/avrdude.conf"

 

         Using Port                    : COM6

         Using Programmer              : arduino

         Overriding Baud Rate          : 115200

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x98

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x98

 

avrdude done.  Thank you.

 

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

**Comment by afarhan** [comment]
I think it is a driver problem. The raduino uses ch340 chipset on the usb.
Is your usb port properly selected? These are usually issues around those.
Having a separate setup routine for the blind could confuse them. It might
be easier to just force it (for instance by holding down the morse key on
bootup).
- f

**Comment by vk7js** [comment]
Hi Farhan,

 

Yes, the com port as already stated is correct and I see the ch340 on the correct com port in device manager.

No, I do not think it confusing for a blind person since they can’t set up the device without cw feedback and could in fact mess up the calibration so I think that holding down the main encoder is the right way to go to enable cw feedback on power on.

Also, they may not have a cw key connected.

Please advise with the following:

1.	Should dc power be connected when uploading?
2.	Should power knob be on or off when uploading?
3.	Which programmer should be selected?
4.	Do we use the new boot loader or the programmer with the old boot loader?

Thanks

Joe

**Comment by vk7js** [comment]
Ok, I figured it out. I had to change the processor to use the old boot loader.

Joe

**Comment by afarhan** [comment]
Oh ok. Nice!

**Comment by vk7js** [comment]
Hi Farhan,

 

It is actually easier for me to base my work off of the modified firmware at

https://github.com/reedbn/ubitxv6

 

Lots of the Morse code feedback is already implemented. I need to make several further adjustments and have already modified it so that holding down the encoder during power on enables morse feedback rather than entering calibration mode since calibration mode can be entered through the menu and there is no other way for a blind person to enable the feedback without sighted help.

I also need to support the touch screen which this version doesn’t support with cw feedback but the rest of the cw feedback is quite good.

Currently it is still almost impossible, certainly very impractical to do direct frequency entry with cw feedback so that is the first thing I will try and fix.

Joe

**Comment by afarhan** [comment]
It might be easier to implement partial or full frequency read out. Another
old timer trick is to use frequency markers. You can pip the speaker
whenever it crosses a 10 khz point. And small ticks on every khz step. That
way, it is easier to get to a freq and force a read out to confirm it.

**Comment by vk7js** [comment]
Hi Farhan,

 

I’m finding that it is almost impossible to support the touch screen with morse feedback because the processor just doesn’t have enough power. Is it at all possible to create a kit with a keypad and screen and knob rather than the touch screen? Also, with a more powerful Arduino board? Perhaps v7? That way we could actually include the talkie library for proper speech feedback. Take a look at the talkie library on github.

 

Joe

**Comment by afarhan** [comment]
Joe,
I am working on a rapsberry pi based radio. My preferred user interface is
command line. I wrap this around various guis. That should work better.
The challenge with keypad is that we don't have enough pins in the arduino
nano.
It might be easier to write a command line utility to control the rig
through the pc. What do you think?

**Comment by vk7js** [comment]
Hi Farhan,

 

No, people want standalone radios.

Surely we could use a usb keypad even for the raspberry pi based radio.

Joe

**Comment by vk7js** [comment]
The issue with the current Arduino is that to direct frequency entry, you need to slowly turn the dial, find the number using cw feedback, press the dial, find the next number, sometimes you make a mistake and then you have to find the backspace, all very inefficient because you need to wait for the cw to finish. I did try interrupting the cw and while it makes it responsive, it is very sensitive and almost impossible to do. If I try using the touch screen, it takes ages to find the numbers and for it to respond with cw feedback.  A direct entry keypad would be much better on a raspberry pi radio and we could also include a speech synthesizer for proper spoken feedback, same with your sdr scanner.

Joe

**Comment by vk7js** [comment]
Hi Ashhar,

I heard that you have been working on the RPi version of the UBitX. I went as far as I could with accessibility with your prior model but never got satisfactory results due to the processing power of the Arduino. I am still willing to help you with the RPi version. I have been working on OpenRTX and AccessibleGD77, adding accessibility to handheld radios running open firmware but there is no good HF solution for accessibility as yet so your project seems promising. I’ll gladly help you but will of course need the hardware.

 

Thanks

Joe

**Comment by afarhan** [comment]
Joe,
I will contact you offline in a few days. This is an important thing to do.
- f
